#!/bin/bash

echo "/* ### WARNING ### GENERATED FILE ### DO NOT MODIFY ###
  This file was generated by generate_icon_h.sh
*/
" > icon.h
gdk-pixbuf-csource --raw --rle --decoder --name=icon ../assets/icons/kaufhansel.png >> icon.h
