INSERT INTO LISTS (NAME, CREATED_AT, CREATED_BY)
VALUES ('Test List', '2021-01-01 08:00:00.00', (SELECT ID FROM USERS WHERE EMAIL = 'test@test.test'));

INSERT INTO LIST_PERMISSIONS (USER_ID, LIST_ID, ROLE, CREATED_AT)
VALUES ((SELECT ID FROM USERS WHERE EMAIL = 'test@test.test'), (SELECT last_insert_rowid()), 'ADMIN', '2021-01-01 08:00:00.00');