# This is a basic workflow to help you get started with Actions

name: Build & Deploy

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
    tags:
      - v*
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:  
  build_frontend:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: flutter_frontend

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0 # Fetch everything

      - name: Set kaufhansel_version environment variable
        run: echo "kaufhansel_version=$(git describe --abbrev=0 --tags | grep -Eo '[0-9]+\.[0-9]+\.[0-9]')" >> $GITHUB_ENV

      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'

      - name: Install Build Tools
        run: sudo apt-get update && sudo apt-get install ninja-build pkg-config libgtk-3-dev libblkid-dev liblzma-dev

      - name: Prepare Android Upload Key
        run: |
          echo "${{ secrets.ANDROID_UPLOAD_KEY_PROPERTIES }}" > ${{runner.workspace}}/kaufhansel/flutter_frontend/android/key.properties
          echo "${{ secrets.ANDROID_UPLOAD_KEY }}" > ${{runner.workspace}}/upload_key_base64
          base64 -d ${{runner.workspace}}/upload_key_base64 > ${{runner.workspace}}/kaufhansel/flutter_frontend/android/upload_key.jks

      - name: Build Flutter Frontend
        uses: subosito/flutter-action@v1.4.0
        with:
          channel: 'dev'
  
      - run: flutter config --enable-linux-desktop
      - run: flutter pub get
      - run: flutter test --coverage
      - run: flutter build linux --release --split-debug-info=build/debuginfo/linux/
      - run: flutter build apk --release --split-debug-info=build/debuginfo/android/ --build-name ${{env.kaufhansel_version}} --build-number $GITHUB_RUN_NUMBER
      - run: flutter build appbundle --release --split-debug-info=build/debuginfo/android/ --build-name ${{env.kaufhansel_version}} --build-number $GITHUB_RUN_NUMBER
        
      - name: Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.COVERALLS_GITHUB_TOKEN }}
          path-to-lcov: ${{runner.workspace}}/kaufhansel/flutter_frontend/coverage/lcov.info

      - uses: actions/upload-artifact@v2
        with:
          name: frontend-android
          path: |
            ${{runner.workspace}}/kaufhansel/flutter_frontend/build/app/outputs/flutter-apk/app-release.apk
            ${{runner.workspace}}/kaufhansel/flutter_frontend/build/app/outputs/bundle/release/app-release.aab
            ${{runner.workspace}}/kaufhansel/flutter_frontend/build/app/outputs/mapping/release/mapping.txt
          if-no-files-found: error
          
      - uses: actions/upload-artifact@v2
        with:
          name: frontend-linux
          path: ${{runner.workspace}}/kaufhansel/flutter_frontend/build/linux/x64/release/bundle/
          if-no-files-found: error


  build_backend:
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set kaufhansel_version environment variable
        run: echo "kaufhansel_version=$(git describe --abbrev=0 --tags | grep -Eo '[0-9]+\.[0-9]+\.[0-9]')" >> $GITHUB_ENV

      - uses: actions/setup-java@v1
        with:
          java-version: '11.x'
          
      - uses: actions/setup-node@v2
        with:
          node-version: '12'

      - name: Install Build Tools
        run: sudo npm install -g yarn

      - name: Build Backend
        run: ./gradlew -PbackendVersion=${{env.kaufhansel_version}} bundle
        
      - uses: actions/upload-artifact@v2
        with:
          name: backend
          path: |
            ${{runner.workspace}}/kaufhansel/backend/build/libs/*.jar
            ${{runner.workspace}}/kaufhansel/backend/kaufhansel.service
            ${{runner.workspace}}/kaufhansel/backend/kaufhansel_service_config
          if-no-files-found: error

  deploy:
    runs-on: ubuntu-latest
    needs: [build_frontend, build_backend]
    if: github.event_name == 'push' && contains(github.ref, 'refs/tags/v')

    steps:
      - name: Setup SSH key
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_KEY" > ~/.ssh/deploy.key
          chmod 600 ~/.ssh/deploy.key
          cat >>~/.ssh/config <<END
          Host deploy
            HostName $SSH_HOST
            User kaufhansel_deploybot
            IdentityFile ~/.ssh/deploy.key
            StrictHostKeyChecking no
          END
        env:
          SSH_KEY: ${{ secrets.DEPLOY_SSH_KEY }}
          SSH_HOST: ${{ secrets.DEPLOY_SSH_HOST }}

      - name: Download backend
        uses: actions/download-artifact@v2
        with:
          name: backend

      - name: Download android frontend
        uses: actions/download-artifact@v2
        with:
          name: frontend-android

      - name: Download linux frontend
        uses: actions/download-artifact@v2
        with:
          name: frontend-linux
          path: frontend-linux/

      - name: Deploy
        run: |
          ssh deploy 'cp /opt/kaufhansel/kaufhansel_backend.jar /opt/kaufhansel/kaufhansel_backend.jar.bak'
          scp build/libs/kaufhansel_backend.jar deploy:/opt/kaufhansel/kaufhansel_backend.jar
          ssh deploy 'chown kaufhansel_deploybot:kaufhansel_admin /opt/kaufhansel/kaufhansel_backend.jar'

          ssh deploy 'cp /opt/kaufhansel/downloads/kaufhansel.apk /opt/kaufhansel/downloads/kaufhansel.apk.bak'
          scp flutter-apk/app-release.apk deploy:/opt/kaufhansel/downloads/kaufhansel.apk
          ssh deploy 'chown kaufhansel_deploybot:kaufhansel_admin /opt/kaufhansel/downloads/kaufhansel.apk'

          mv frontend-linux kaufhansel-linux
          zip -r kaufhansel-linux.zip kaufhansel-linux/
          scp kaufhansel-linux.zip deploy:/opt/kaufhansel/downloads/kaufhansel-linux.zip
          ssh deploy 'chown kaufhansel_deploybot:kaufhansel_admin /opt/kaufhansel/downloads/kaufhansel-linux.zip'

          ssh deploy 'sudo systemctl restart kaufhansel'

      - uses: r0adkll/upload-google-play@v1
        with:
          serviceAccountJsonPlainText: ${{ secrets.PLAY_STORE_SERVICE_ACCOUNT_KEY_JSON }}
          packageName: de.zwohansel.kaufhansel.kaufhansel_client
          releaseFiles: bundle/release/app-release.aab
          track: internal
          inAppUpdatePriority: 2
          #userFraction: 0.33
          #whatsNewDirectory: distribution/whatsnew
          mappingFile: mapping/release/mapping.txt

