# This is a basic workflow to help you get started with Actions

name: Build & Deploy

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
    tags:
      - v*
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:  
  build_frontend:
    runs-on: ubuntu-latest
    if: false # TODO: Fix flutter build

    defaults:
      run:
        working-directory: flutter_frontend

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Fetch everything

      - name: Set kaufhansel_version environment variable
        run: echo "kaufhansel_version=$(git describe --abbrev=0 --tags | grep -Eo '[0-9]+\.[0-9]+\.[0-9]')" >> $GITHUB_ENV

      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Install Build Tools
        run: sudo apt-get update && sudo apt-get install ninja-build pkg-config libgtk-3-dev libblkid-dev liblzma-dev lcov

      - name: Prepare Android Upload Key
        run: |
          echo "${{ secrets.ANDROID_UPLOAD_KEY_PROPERTIES }}" > ${{runner.workspace}}/kaufhansel/flutter_frontend/android/key.properties
          echo "${{ secrets.ANDROID_UPLOAD_KEY }}" > ${{runner.workspace}}/upload_key_base64
          base64 -d ${{runner.workspace}}/upload_key_base64 > ${{runner.workspace}}/kaufhansel/flutter_frontend/android/upload_key.jks

      - name: Build Flutter Frontend
        uses: subosito/flutter-action@v1.4.0
        with:
          channel: 'stable'
          flutter-version: '2.0.5'
      - run: flutter config --enable-linux-desktop
      - run: flutter pub get
      - run: flutter test --coverage
      - run: flutter build linux --release --split-debug-info=build/debuginfo/linux/
      - run: flutter build apk --release --split-debug-info=build/debuginfo/android/ --build-name ${{env.kaufhansel_version}} --build-number $GITHUB_RUN_NUMBER
      - run: flutter build appbundle --release --split-debug-info=build/debuginfo/android/ --build-name ${{env.kaufhansel_version}} --build-number $GITHUB_RUN_NUMBER
        
      - name: Remove generated code from coverage
        run: lcov --remove ${{runner.workspace}}/kaufhansel/flutter_frontend/coverage/lcov.info '*/generated/*' -o ${{runner.workspace}}/kaufhansel/flutter_frontend/coverage/lcov_filtered.info

      - name: Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: ${{runner.workspace}}/kaufhansel/flutter_frontend/coverage/lcov_filtered.info
          base-path: ${{runner.workspace}}/kaufhansel/flutter_frontend/

      - uses: actions/upload-artifact@v4
        with:
          name: frontend-android
          path: |
            ${{runner.workspace}}/kaufhansel/flutter_frontend/build/app/outputs/flutter-apk/app-release.apk
            ${{runner.workspace}}/kaufhansel/flutter_frontend/build/app/outputs/bundle/release/app-release.aab
            ${{runner.workspace}}/kaufhansel/flutter_frontend/build/app/outputs/mapping/release/mapping.txt
          if-no-files-found: error
          
      - uses: actions/upload-artifact@v4
        with:
          name: frontend-linux
          path: ${{runner.workspace}}/kaufhansel/flutter_frontend/build/linux/release/bundle/
          if-no-files-found: error


  build_backend:
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set kaufhansel_version environment variable
        run: echo "kaufhansel_version=$(git describe --abbrev=0 --tags | grep -Eo '[0-9]+\.[0-9]+\.[0-9]')" >> $GITHUB_ENV

      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build Backend
        run: ./gradlew -PbackendVersion=${{env.kaufhansel_version}} bundle
        
      - uses: actions/upload-artifact@v4
        with:
          name: backend
          path: |
            ${{runner.workspace}}/kaufhansel/backend/build/libs/*.jar
          if-no-files-found: error

  deploy:
    runs-on: ubuntu-latest
    #needs: [build_frontend, build_backend]
    needs: [build_backend]
    if: github.event_name == 'push' && contains(github.ref, 'refs/tags/v')

    steps:
      - name: Setup SSH key
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_KEY" > ~/.ssh/deploy.key
          chmod 600 ~/.ssh/deploy.key
          cat >>~/.ssh/config <<END
          Host deploy
            HostName $SSH_HOST
            User $KAUFHANSEL_DEPLOY_USER
            IdentityFile ~/.ssh/deploy.key
            StrictHostKeyChecking no
          END
        env:
          SSH_KEY: ${{ secrets.DEPLOY_SSH_KEY }}
          SSH_HOST: ${{ secrets.DEPLOY_SSH_HOST }}
          KAUFHANSEL_DEPLOY_USER: ${{ secrets.KAUFHANSEL_DEPLOY_USER }}

      - name: Download backend
        uses: actions/download-artifact@v4
        with:
          name: backend

      #- name: Download android frontend
      #  uses: actions/download-artifact@v4
      #  with:
      #    name: frontend-android

      #- name: Download linux frontend
      #  uses: actions/download-artifact@v4
      #  with:
      #    name: frontend-linux
      #    path: frontend-linux/

      - name: Deploy
        run: |
          rsync kaufhansel_backend.jar deploy:/home/$KAUFHANSEL_DEPLOY_USER/kaufhansel/kaufhansel_backend.jar

          #ssh deploy "mkdir -p /home/$KAUFHANSEL_DEPLOY_USER/kaufhansel/downloads"
          #rsync flutter-apk/app-release.apk deploy:/home/$KAUFHANSEL_DEPLOY_USER/kaufhansel/downloads/kaufhansel.apk

          #mv frontend-linux kaufhansel-linux
          #zip -r kaufhansel-linux.zip kaufhansel-linux/
          #rsync kaufhansel-linux.zip deploy:/home/$KAUFHANSEL_DEPLOY_USER/kaufhansel/downloads/kaufhansel-linux.zip

          ssh deploy "docker stop kaufhansel || true"
          ssh deploy "docker run --detach --rm --name kaufhansel --log-driver=journald --network $KAUFHANSEL_DOCKER_NETWORK -e KAUFHANSEL_MAIL_SERVER_HOST=$KAUFHANSEL_MAIL_SERVER_HOST -e KAUFHANSEL_MAIL_SERVER_PORT=$KAUFHANSEL_MAIL_SERVER_PORT -e KAUFHANSEL_MAIL_USERNAME=$KAUFHANSEL_MAIL_USERNAME -e KAUFHANSEL_MAIL_PASSWORD=$KAUFHANSEL_MAIL_PASSWORD -e KAUFHANSEL_TOKEN_SECRET=$KAUFHANSEL_TOKEN_SECRET --volume /home/$KAUFHANSEL_DEPLOY_USER/kaufhansel:/kaufhansel --workdir /kaufhansel eclipse-temurin:17 java -jar kaufhansel_backend.jar"
        env:
          KAUFHANSEL_MAIL_USERNAME: ${{ secrets.KAUFHANSEL_MAIL_USERNAME }}
          KAUFHANSEL_MAIL_PASSWORD: ${{ secrets.KAUFHANSEL_MAIL_PASSWORD }}
          KAUFHANSEL_TOKEN_SECRET: ${{ secrets.KAUFHANSEL_TOKEN_SECRET }}
          KAUFHANSEL_DEPLOY_USER: ${{ secrets.KAUFHANSEL_DEPLOY_USER }}
          KAUFHANSEL_DOCKER_NETWORK: ${{ vars.KAUFHANSEL_DOCKER_NETWORK }}
          KAUFHANSEL_MAIL_SERVER_HOST: ${{ vars.KAUFHANSEL_MAIL_SERVER_HOST }}
          KAUFHANSEL_MAIL_SERVER_PORT: ${{ vars.KAUFHANSEL_MAIL_SERVER_PORT }}

      #- uses: r0adkll/upload-google-play@v1
      #  with:
      #    serviceAccountJsonPlainText: ${{ secrets.PLAY_STORE_SERVICE_ACCOUNT_KEY_JSON }}
      #    packageName: de.zwohansel.kaufhansel.kaufhansel_client
      #    releaseFiles: bundle/release/app-release.aab
      #    track: internal
      #    inAppUpdatePriority: 2
      #    status: completed
      #    #userFraction: 0.33
      #    #whatsNewDirectory: distribution/whatsnew
      #    mappingFile: mapping/release/mapping.txt

