# This is a basic workflow to help you get started with Actions

name: Build & Deploy

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
    tags:
      - v*
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:  
  build:
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set kaufhansel_version environment variable
        run: echo "kaufhansel_version=$(git describe --abbrev=0 --tags | grep -Eo '[0-9]+\.[0-9]+\.[0-9]')" >> $GITHUB_ENV

      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'
          
      - uses: actions/setup-node@v2
        with:
          node-version: '12'

      - name: Install Build Tools
        run: sudo apt-get update && sudo apt-get install ninja-build pkg-config libgtk-3-dev libblkid-dev liblzma-dev && sudo npm install -g yarn

      - name: Build Backend
        run: ./gradlew -PbackendVersion=${{env.kaufhansel_version}} bundle
        
      - uses: actions/upload-artifact@v2
        with:
          name: backend
          path: |
            ${{runner.workspace}}/kaufhansel/backend/build/libs/*.jar
            ${{runner.workspace}}/kaufhansel/backend/kaufhansel.service
            ${{runner.workspace}}/kaufhansel/backend/kaufhansel_service_config
          if-no-files-found: error
        
      - name: Build Flutter Frontend
        uses: subosito/flutter-action@v1.4.0
        with:
          channel: 'dev'
  
      - run: flutter config --enable-linux-desktop
      - run: flutter pub get
      - run: flutter test
      - run: flutter build linux --release --split-debug-info=build/debuginfo/linux/
      - run: flutter build apk --release --split-debug-info=build/debuginfo/android/ --build-name ${{env.kaufhansel_version}} --build-number $GITHUB_RUN_NUMBER
        
      - uses: actions/upload-artifact@v2
        with:
          name: frontend-android
          path: ${{runner.workspace}}/kaufhansel/flutter_frontend/build/app/outputs/flutter-apk/app-release.apk
          if-no-files-found: error
          
      - uses: actions/upload-artifact@v2
        with:
          name: frontend-linux
          path: ${{runner.workspace}}/kaufhansel/flutter_frontend/build/linux/release/bundle/
          if-no-files-found: error
